## INPUTS
input UpdateUserInput {
	username: String
	avatar: String
	email: String
}

input AuthProfileInput {
	email: String
}

## TYPES
type User {
	username: String
	avatar: String
	email: String
}

type PublicProfile {
	username: String
}

## ROOT
extend type Query {
	getUserProfile(id: ID!): User
	getPublicProfile(id: ID!): PublicProfile
}

extend type Mutation {
	loginUser(id: ID!, input: AuthProfileInput): User
	logoutUser(id: ID!): User
	updateUser(id: ID!, input: UpdateUserInput): User
	removeUser(id: ID!): User
}
